export const DATA_SOURCE = 'DATA_SOURCE';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const PROFILE_REPOSITORY = 'PROFILE_REPOSITORY';
export const MATCH_REPOSITORY = 'MATCH_REPOSITORY';
export const CHAT_REPOSITORY = 'CHAT_REPOSITORY';
export const CHAT_USER_REPOSITORY = 'CHAT_USER_REPOSITORY';
